[[redirects]]
  from = "/post/2019-11-02_golf-turing/"
  to = "/posts/2019-11-02-golf-turing/"
  status = 301
  force = true
  
[[redirects]]
  from = "/post/2019-03-26_market-dem-with-iv/"
  to = "/posts/2019-03-26-market-dem-with-iv/"
  status = 301
  force = true
  
[[redirects]]
  from = "/post/2019-03-16_kde-scratch"
  to = "/posts/2019-03-16-kde-scratch"
  status = 301
  force = true